name: Test and review python workflow

on: push

jobs:
  job_python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code on runner VM
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set the Python path
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest tests --cov=app --cov-report=xml
          

      # GITHUB_WORKSPACE : it is a default directory on the runner where your repository is checked out
      # It is automatically set by Github Actions and points to the root of your repoistory 
      # In this Workflow, we are adding the GITHUB_WORKSPACE to the PYTHONPATH enviroment variable
      # so that Python can locate your modules and packages during testing

      #here $GITHUB_ENV is a special file that Github actions
      # uses to set environment variables for subsequent steps in the workflow

